use rapids;

insert into users 
	(username, password, email, salt) 
	values
	('bab7607', 'fc79998161c986a0c1f52bf7cce07dc34528ddabecfa31e396731e83a9f3f7f2', 'bab7607@rit.edu', 'nklv84sw5j'),
	('csn6973', '753b71337dfa87a3495d115bd559aedfa4bb14f8591e0ffbdddd9969cbc29ed1', 'csn6973@rit.edu', 'd5g1jbp2sh'),
	('fxb5214', '31fa6dcdad0310ebc8f016118e6f57919283e214a3c6f3d02d5ce05aa6be00be', 'fxb5214@rit.edu', 'v2ah852ded'),
	('jxb7623', '8e633436912777412f71c80633a02673212357b16e66c081bcfb82bf736307d7', 'jxb7623@rit.edu', 'efp26qr2hj'),
	('pxc8399', '5ef8d8f19397dd82bc5646039208ba88b30705a578b10c6cc82ce73edd73429b', 'pxc8399@rit.edu', 'q28m2rl5f5'),
	('yxd1196', 'f67e14f90e4d5cc09dfce3eca7ad4ef0b46aa21e2e980b58d5844cc18b33248d', 'yxd1196@rit.edu', 'iafhio6562');
	
insert into pins 
	(lat, lon, filters, image, name, summary, content)
	values
	(43.129519, -77.639381, 'War, The Revolutionary War', 'https://assets.entrepreneur.com/content/3x2/1300/20150406145944-dos-donts-taking-perfect-linkedin-profile-picture-selfie-mobile-camera-2.jpeg',
	'George Gordon', 'Gordon, George C., president of the First National Bank of Brockport, was born in Rushford.', 'Gordon, George C., president of the First National Bank of Brockport, was born in Rushford, Allegany county, July 1, 1849, and his father, Luther Gordon, was a native of the same place. The grandfather, John, came from Cavendish, Vt., about 1809. In 1809 John G. visited the site of Rochester, but not liking it, settled in Rushford. Luther Gordon, the second son, formed a partnership with Samuel White in the furnace business, during which he invented the Genesee Plow. Disposing of the furnace business, he afterwards erected a large store at Rushford and engaged in general merchandise and the buying and shipping of stock. In 1856 he bought the lumber business of Boswell, Walker & Hood at Brockport, and in 1858 erected the family residence, to which he removed his family a year later. For some time he gave his attention to the lumber business, buying large tracts of western lands, mostly in Michigan. In 1863 he organized the first National, Bank of Brockport, and was elected president, which office he held to the time of his death, March 26, 1881. He married Florilla Cooley of Attica, Wyoming county, who died in 1869, leaving one son, George C. The latter was educated at Brockport College, and finished with a business course in Rochester. In 1874 he married Ida M., daughter of Thomas C. Hooker, and they have these children: Luther, George C., jr., William H., Frederick H., Thomas C., of whom William H. died in infancy. In 1881 our subject was elected president of the bank, which office he now fills, having begun his banking experience with Waters, Bishop & Co. In June, 1863, he was assaulted by thieves, thrown into the vault, and when aid reached him life was nearly extinct. Mr. Gordon is the leading business man of his town, and interested in all that tends to its advancement.'),
	(43.129483, -77.639393, 'War, The Revolutionary War, War of 1812', 'http://static2.businessinsider.com/image/5899ffcf6e09a897008b5c04-1200/.jpg',
	'Alonzo  Raymond', 'Raymond, Alonzo B., was born in Chenango county, July 18, 1819.', 'Raymond, Alonzo B., was born in Chenango county, July 18, 1819. His father, Alphius, was born in Massachusetts, and married a Miss Daniels. They first settled in McDonough, Chenango county, but in 1830 came to Monroe county and settled in the town of Byron, and later in Parma. Alonzo B. was educated in the common schools and is pre-eminently a self-made man. At the age of nineteen he began teaching school, and continued for four years; was engaged in the mercantile business at North Parma, Spencerport, and Adams Basin for about twelve years, after which he confined himself to dealing in produce. In the spring of 1860 he was appointed pastor of the Universalist Church at Portage, Wyoming county, remaining in the ministry four years, after which he again engaged in the produce business and has so continued. In 1843 he married Elizabeth A., daughter of Samuel Wyman, and their children are A. Clayton, attorney at Detroit, Mich., counsel for the Grand Trunk and Canadian Pacific Railroad; and George H., of Buffalo. Our subject is one of the representative men of the town.'),
	(43.129485, -77.639337, 'War, The Revolutionary War', 'https://www.lawlogix.com/wp-content/uploads/2015/05/LW-603-p28-partner-profile.jpg',
	'Holmes Daniel', 'Holmes, Daniel, was born in West Bloomfield, September 11, 1828, a son of Daniel, sr., a native of Massachusetts. ', 'Holmes, Daniel, was born in West Bloomfield, September 11, 1828, a son of Daniel, sr., a native of Massachusetts, who, with his father, Alpheus, came to Ontario about 1811, among the pioneer settlers of that town. Daniel, sr., served in the war of 1812, and was at the burning of Buffalo by the British. He married Susan Stuart. Daniel, jr., was educated at Brockport Collegiate Institute in 1846, and was graduated from Yale College in 1848, after which he taught school in Woodford county; Ky., for two and a half years, spent a year in Canandaigua as professor of Latin, and then began the study of law. He was admitted to the bar in 1852, and married Mary J. Hawes of Brookfield, Mass., the well-known writer of fiction. Our subject has served in various positions of public trust and responsibility, and is regarded as one of the cultured and intelligent men of the town.'),
	(43.129440, -77.639277, 'War, War 12', 'https://www.fotkaplus.co.uk/wp-content/uploads/2016/04/carousel-profile-4.jpg',
	'Dorwain Richards', 'Richards, Dorwain, was born in Fulton county, N. Y., March 11, 1844.', 'Richards, Dorwain, was born in Fulton county, N. Y., March 11, 1844, a son of Rev. William I. Richards, a native of Vermont, who came to Monroe county in 1860, and settled in the town of Clarkson, where he bought a farm, and remained to recover his health. In 1863 he resumed his labors in the ministry, which were continued up to the date of his death in 1875. Dorwain Richards was educated in the public schools, to which he has added by reading and close observation. In August, 1862, he enlisted in Co. A, 140th N. Y. Vols., and participated in the battles of Fredericksburg, Chancellorsville, Gettysburg, Mine Run, and the Wilderness, receiving an honorable discharge in 1865 at the close of the war, returning to the farm, where he remained till 1875. He then came to Brockport, and entered the employ of D. S. Morgan, remaining till 1888, then established his present business, carrying a, full line of fire, life, and accident insurance, and deals also in real estate. In 1868 he married Jane E. Moore, and their children are Mrs. Mabel B. Mitchell, and Jessie G. Richards.'),
	(43.129450, -77.639240, 'Plants', 'https://maxpull-tlu7l6lqiu.stackpathdns.com/wp-content/uploads/2017/06/zone-9-lilac.jpg',
	'Lilac', 'Lilacs have a deep rooted history originating in ancient Greek mythology. ', 'Lilacs have a deep rooted history originating in ancient Greek mythology. It was said that Pan, the god of forests and fields was hopelessly in love with a nymph named Syringa. One day he was pursuing her through a forest and, afraid of his advances, she turned herself into a lilac shrub to disguise herself.'),
	(43.129465, -77.639310, 'Plants', 'https://i.pinimg.com/originals/05/41/12/054112201b64997b770cab1fdc371c48.jpg',
	'Lilium', 'Lilium (members of which are true lilies) is a genus of herbaceous flowering plants growing from bulbs, all with large prominent flowers.', 'Lilium (members of which are true lilies) is a genus of herbaceous flowering plants growing from bulbs, all with large prominent flowers. Lilies are a group of flowering plants which are important in culture and literature in much of the world. Most species are native to the temperate northern hemisphere, though their range extends into the northern subtropics. Many other plants have "lily" in their common name but are not related to true lilies.'),
	(43.129502, -77.639390, 'Plants', 'https://foodtoglow.files.wordpress.com/2015/03/img_20150316_175315.jpg',
	'Garlic', 'A number of different plant species of the genus Allium are known as wild garlic.', 'A number of different plant species of the genus Allium are known as wild garlic. Wild garlic is also a common name for plants in the genus Tulbag.');

insert into content
	(page, dataType, text)
	values
	('Home', 'Large_Title', 'Rapids Cemetery'),
	('Home', 'Medium_Title', 'Rochester, New York'),
	('Home', 'Image', 'https://assets.entrepreneur.com/content/3x2/1300/20150406145944-dos-donts-taking-perfect-linkedin-profile-picture-selfie-mobile-camera-2.jpeg'),
	('Home', 'Paragraph', 'This cemetery is located on the north side of Congress Avenue on the west side of the City of Rochester, N. Y.'),
	('Home', 'Paragraph', 'This cemetery was probably founded between 1810 and 1812. The property was originally owned by the Wadsworth family which owned land from Geneseo to Rochester. The Wadsworths set aside one and a quarter acre for a burial place of area residents. The cemetery resided in the Town of Gates until 1902 when the area was annexed into the City of Rochester. The road leading to the cemetery was originally called Cemetery Road. Then between 1880 and 1890 the name was changed to Chester Street. In 1899, Chester Street became Congress Avenue.'),
	('Home', 'Paragraph', 'On 20 September 1883 Herbert and William Wadsworth sold the cemetery lot to the newly formed "Rapids Cemetery Association." Monroe H. Oakley was the first president of the organization and Isaac Loomis was treasurer. The last known record of the Rapids Cemetery Association was in 1900 when they paid property taxes. The map, below, was traced from one probably made in the 1890s, although the exact date is unknown. It also included a list of plot owner, which relate to the map.'),
	('Home', 'Paragraph', 'Almost all the tombstones have been knocked over. The listing of tombstone inscriptions below was made from old transcriptions and a visit to the cemetery in the late 1980s.'),
	('Home', 'Medium_Title', 'Rochester\'s \'forgotten\' land: the Rapids Cemetery'),
	('Home', 'Paragraph', 'This is the story of a piece of land that nobody wanted, a little patch of green in the heart of Rochester\'s west side that may have tremendous significance in this Bicentennial year, but which is now little more than a refuse heap.'),
	('Home', 'Paragraph', 'It is called the "Rapids Cemetery." Located at 65 Congress Avenue, it is older than the City of Rochester itself. But those few people who know what and where it is are lost among the hundreds of cars, pedestrians, and neighborhood kids who pass it every day, totally unaware.'),
	('Home', 'Paragraph', 'To most, it is just a brief gap of sunlight in the middle of a shady westside block.'),
	('About_Us', 'Large_Title', 'About Us'),
	('About_Us', 'Medium_Title', 'About the USGenWeb Project'),
	('About_Us', 'Link', 'http://google.com'),
	('About_Us', 'Paragraph', 'In March and April, 1996, a group of genealogists from Kentucky began organizing web pages for each county in their similar pages. Almost every county in the US and Canada has a GenWeb page. Then the GenWeb project went world wide and there are similar pages for most countries on our planet. All GenWeb pages are staffed by volunteers helping people to find their families.'),
	('Nearby_Historical_Trails', 'Large_Title', 'Nearby Historical Trails'),
	('Nearby_Historical_Trails', 'Paragraph', 'There are maps of the Towns in Monroe County. There are also a few more maps listed on the links page.These are the maps that are here on the GenWeb of Monroe County. Besides these maps, there are many cemetery maps on the Cemetery Page and links to maps on other websites on the Links Page.'),
	('Tombstones_&_Natural_History', 'Large_Title', 'Tombstones & Natural History'),
	('Tombstones_&_Natural_History', 'Medium_Title', 'Tombstones'),
	('Tombstones_&_Natural_History', 'Link', 'http://google.com'),
	('Tombstones_&_Natural_History', 'Paragraph', 'There are many cemetery records. Most are lists of tombstone inscriptions but a few also include burial records. Not every cemetery is available and probably never will be as some are very large.'),
	('Tombstones_&_Natural_History', 'Paragraph', 'Some cemeteries have links to on-line maps from MapQuest and Google Maps which can be used to find the location of the cemetery and also to get directions to the cemetery. Included are GPS coordinates. If you need GPS coordinates in a different format, use this website to translate them to your format.'),
	('Tombstones_&_Natural_History', 'Medium_Title', 'Flowers and Plants'),
	('Tombstones_&_Natural_History', 'Paragraph', 'A flower, sometimes known as a bloom or blossom, is the reproductive structure found in flowering plants (plants of the division Magnoliophyta, also called angiosperms). The biological function of a flower is to effect reproduction, usually by providing a mechanism for the union of sperm with eggs. Flowers may facilitate outcrossing (fusion of sperm and eggs from different individuals in a population) or allow selfing (fusion of sperm and egg from the same flower). Some flowers produce diaspores without fertilization (parthenocarpy). Flowers contain sporangia and are the site where gametophytes develop. Many flowers have evolved to be attractive to animals, so as to cause them to be vectors for the transfer of pollen. After fertilization, the ovary of the flower develops into fruit containing seeds.'),
	('Tombstones_&_Natural_History', 'Image', 'https://maxpull-tlu7l6lqiu.stackpathdns.com/wp-content/uploads/2017/06/zone-9-lilac.jpg');


